export { Genre } from './ui/Genre/Genre'
export { Rating } from './ui/Rating/Rating'
export { Title } from './ui/Title/Title'
export { Button } from './ui/Button/Button'
export { Slider } from './Slider/Slider'
export { Spinner } from './ui/Spinner/Spinner'
export { PaginatedSlider } from './PaginatedSlider/PaginatedSlider'
